<?xml version="1.0"?>
<package format="3">
  <name>maize_navigation</name>
  <version>0.0.1</version>
  <description>Single-node maize row navigation prototype with row acquisition.</description>

  <maintainer email="tzimmerman@stud.hs-heilbronn.de">FRE2026 Team</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>maize_navigation_interfaces</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>visualization_msgs</depend>
  <depend>fre2026_detection_client</depend>
  <depend>tf2_ros</depend>
  <depend>tf_transformations</depend>
  <depend>python3-numpy</depend>
  <depend>python3-scipy</depend>
  <depend>fre2026_tasks_interfaces</depend>

  <exec_depend>ros-jazzy-tf-transformations</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
